import React, { useContext } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { ChatRoom } from "../components/ChatRoom";
import { MailSubmission } from "../components/MailSubmission";
import { Switch, Image } from "@chakra-ui/react";
import { ThemeContext } from "./_app";

interface PageProps {
  authentication: "user" | "guest";
  changeTheme: () => void;
}

const Home: NextPage<PageProps> = ({ authentication, changeTheme }) => {
  const theme = useContext(ThemeContext);

  const renderContent = () => {
    switch (authentication) {
      case "guest":
        return <MailSubmission />;
      case "user":
        return <ChatRoom />;
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Next/Flutter/Go chat system</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/random.png" />
      </Head>
      <main className={styles.main}>
        <Image alt="logo" src="/logo.png" />
        <h1 className={styles.title}>Next/Flutter/Go chat system</h1>
        <Switch
          isChecked={theme === "dark"}
          onChange={changeTheme}
          className={styles.theme}
        >
          Night mode
        </Switch>
        {renderContent()}
      </main>

      <footer className={styles.footer}>
        <div>Powered by</div>
        <span className={styles.logo}>
          <Image src="/logo.png" alt="Vercel Logo" width={100} height={50} />
        </span>
      </footer>
    </div>
  );
};

export default Home;
